### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anomalchik** [freemarkw/android_device_xiaomi_markw#1]
## **Device**
- [x]   Audio(need amplifier hook to audio hal)
- [x]   MAC (BT)
- [x]   Fingerprints
- [x]   Leds
- [x]   disable navbar
- [x]   power hal
- [x]   adsprpc
- [x]   add customized markw led driver
- [x]   Camera (Thanks to @nichcream, @SonicBSV, @efaiza)
- [x]   atmel multitouch
- [x]   power driver
- [x]   Symliniks
- [x]   Treble
- [x]   Rewrite LEDs hal to service
- [x]   Rewrite OLDLEDs hal to service
- [x]   Write oss consumerir service
- [x]   HAL3: ISP40: color_correct flickering (thx @HighwayStar_ru)
- [x]   Add correct hires support
- [x]   Add support for 720p / 1080p @ 60 video
- [x]   Update gps and gnsspps 
- [x]   Selinux rules (updated)
- [x]   Selinux enforcing
- [x]   User build varian
- [x]   Compass don't save calibration

## **GSI**
- [-]   init: override device specific properties if gsi rom - **del**

**Comment by anomalchik** [comment]
Camera log 
https://gist.github.com/anomalchik/6a6d3e4dd2603ade2450efe854a9615d

**Comment by anomalchik** [comment]
nougat camera log
https://gist.github.com/anomalchik/d6535cf64417646e58f174622f240be5

**Comment by ghost** [comment]
This is some good kernel here. :)

**Comment by vfr456** [comment]
Call volume is too load when using headphone
